<link type="text/css" rel="stylesheet" href="css/main.css" />
<link type="text/css" rel="stylesheet" href="css/forms.css" />
</head>
<body>
<section id="login" >
	<img src="image/SQLAssistLogo.png">
	<form method="post" id="loginForm" action="index.php">
		<p>
			<label>Username:</label>
			<input type="text" name="username" id="username" value="" placeholder="username" />
		</p>
		<p>
			<label>Password:</label>
			<input type="password" name="pwd" id="pwd" value="" placeholder="password" />
		</p>			
		<p><input type="submit" name="login" id="loginButton" /></p>
	</form>
</section>
<!-- script type="text/javascript" src="js/interface.js"></script -->
<script type="text/javascript" src="js/login.js"></script>